import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  items: [
    // --- ELECTRONICS (Vendor: Tech Haven) ---
    {
      id: "p_1001",
      title: "Wireless Noise-Cancelling Headphones",
      description:
        "Premium over-ear headphones with active noise cancellation.",
      price: 249.99,
      images: ["https://picsum.photos/seed/p_1001/800/800"],
      category: "Electronics",
      brand: "SoundMakers",
      stock: 0,
      rating: 4.8,
      reviewCount: 124,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-06T10:00:00Z",
      salesCount: 150,
      color: ["Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      storage: "None",
      ram: "None",
      screenSize: "None",
      condition: "New",
      productDetails: [
        "Battery Life: Up to 30 hours of continuous playback",
        "Connectivity: Bluetooth 5.2 and 3.5mm wired option",
        "Charging: USB-C fast charging (5 mins = 2 hours play)",
        "Microphone: 4 built-in mics for crystal clear calls",
        "Weight: 250 grams",
      ],
    },
    {
      id: "p_1002",
      title: "Minimalist Mechanical Keyboard",
      description: "Tenkeyless mechanical keyboard with tactile switches.",
      price: 129.0,
      images: ["https://picsum.photos/seed/p_1002/800/800"],
      category: "Electronics",
      brand: "Keychron",
      stock: 15,
      rating: 4.7,
      reviewCount: 89,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-15T10:00:00Z",
      salesCount: 80,
      color: ["White", "Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      storage: "None",
      ram: "None",
      screenSize: "None",
      condition: "Refurbished",
      productDetails: [
        "Switches: Hot-swappable tactile brown switches",
        "Layout: 87-key Tenkeyless (TKL)",
        "Backlight: White LED with 15 modes",
        "Material: Aluminum frame with PBT keycaps",
        "Connectivity: Wired USB-C",
      ],
    },
    {
      id: "p_1003",
      title: "Smartphone Pro Max 5G",
      description: "Latest flagship with incredible camera.",
      price: 999.0,
      images: ["https://picsum.photos/seed/p_1003/800/800"],
      category: "Electronics",
      brand: "Visionary",
      stock: 60,
      rating: 4.6,
      reviewCount: 210,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-07T10:00:00Z",
      salesCount: 200,
      color: ["Black", "Blue"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      storage: "256GB",
      ram: "8GB",
      screenSize: "6.7 inch",
      condition: "New",
    },
    {
      id: "p_1004",
      title: "4K Ultra HD Webcam",
      description:
        "Crystal clear video for streaming and professional meetings.",
      price: 199.5,
      images: ["https://picsum.photos/seed/p_1004/800/800"],
      category: "Electronics",
      brand: "Visionary",
      stock: 0,
      rating: 4.4,
      reviewCount: 56,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-10T10:00:00Z",
      salesCount: 45,
      color: ["Black"],
      size: [],
      dressStyle: "",
      availability: "Out of Stock",
      storage: "None",
      ram: "None",
      screenSize: "None",
      condition: "New",
    },
    {
      id: "p_1005",
      title: "Gaming Laptop Ultra",
      description: "High performance gaming laptop with RTX graphics.",
      price: 1499.99,
      images: ["https://picsum.photos/seed/p_1005/800/800"],
      category: "Electronics",
      brand: "TechHaven",
      stock: 0,
      rating: 4.8,
      reviewCount: 340,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-01T10:00:00Z",
      salesCount: 310,
      color: ["Black", "White"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      storage: "1TB",
      ram: "32GB",
      screenSize: "15.6 inch",
      condition: "New",
    },
    {
      id: "p_1006",
      title: "Bluetooth Bookshelf Speakers",
      description: "Rich, room-filling sound with wood grain finish.",
      price: 149.99,
      images: ["https://picsum.photos/seed/p_1006/800/800"],
      category: "Electronics",
      brand: "AudioEngine",
      stock: 12,
      rating: 4.9,
      reviewCount: 77,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-20T10:00:00Z",
      salesCount: 60,
      color: ["Brown", "Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      storage: "None",
      ram: "None",
      screenSize: "None",
      condition: "Used",
    },
    {
      id: "p_1007",
      title: "Tablet Air 10.9",
      description: "Lightweight and powerful tablet for creatives.",
      price: 599.0,
      images: ["https://picsum.photos/seed/p_1007/800/800"],
      category: "Electronics",
      brand: "Visionary",
      stock: 85,
      rating: 4.3,
      reviewCount: 412,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-05T10:00:00Z",
      salesCount: 450,
      color: ["White", "Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      storage: "128GB",
      ram: "4GB",
      screenSize: "10.9 inch",
      condition: "New",
    },
    {
      id: "p_1008",
      title: "Smart Home Hub Display",
      description:
        "Control your smart home devices from one central touchscreen.",
      price: 129.99,
      images: ["https://picsum.photos/seed/p_1008/800/800"],
      category: "Electronics",
      brand: "HomeSync",
      stock: 30,
      rating: 4.5,
      reviewCount: 128,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-25T10:00:00Z",
      salesCount: 115,
      color: ["White"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      storage: "None",
      ram: "None",
      screenSize: "7 inch",
      condition: "New",
    },
    {
      id: "p_1009",
      title: "Desktop Workstation",
      description: "Powerful tower for heavy workloads.",
      price: 899.99,
      images: ["https://picsum.photos/seed/p_1009/800/800"],
      category: "Electronics",
      brand: "TechHaven",
      stock: 300,
      rating: 4.7,
      reviewCount: 890,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-01T10:00:00Z",
      salesCount: 950,
      color: ["Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      storage: "512GB",
      ram: "16GB",
      screenSize: "None",
      condition: "Refurbished",
    },
    {
      id: "p_1010",
      title: "Smartphone Gimbal Stabilizer",
      description: "Shoot smooth, cinematic video with your smartphone.",
      price: 99.0,
      images: ["https://picsum.photos/seed/p_1010/800/800"],
      category: "Electronics",
      brand: "Visionary",
      stock: 22,
      rating: 4.6,
      reviewCount: 65,
      vendor: { vendorId: "v_055", storeName: "Tech Haven", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-04T10:00:00Z",
      salesCount: 75,
      color: ["Black", "White"],
      size: [],
      dressStyle: "",
      availability: "Pre-order",
      storage: "None",
      ram: "None",
      screenSize: "None",
      condition: "New",
    },

    // --- APPAREL (Vendor: Sustainable Basics) ---
    {
      id: "p_2001",
      title: "Organic Cotton Crewneck T-Shirt",
      description: "Breathable, 100% organic cotton t-shirt for everyday wear.",
      price: 24.0,
      images: ["https://picsum.photos/seed/p_2001/800/800"],
      category: "Fashion & Apparel",
      brand: "EcoThread",
      stock: 120,
      rating: 4.5,
      reviewCount: 89,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-08-07T10:00:00Z",
      salesCount: 150,
      color: ["White", "Black", "Blue"],
      size: ["Small", "Medium", "Large"],
      dressStyle: "Casual",
      availability: "In Stock",
      material: "Cotton",
      gender: "Unisex",
      productDetails: [
        "Material: 100% GOTS Certified Organic Cotton",
        "Fit: Regular relaxed fit",
        "Care Instructions: Machine wash cold, tumble dry low",
        "Neckline: Ribbed crewneck",
        "Origin: Responsibly made in Portugal",
      ],
    },
    {
      id: "p_2002",
      title: "Classic Denim Jacket",
      description: "Vintage wash denim jacket with a relaxed fit.",
      price: 79.5,
      images: ["https://picsum.photos/seed/p_2002/800/800"],
      category: "Fashion & Apparel",
      brand: "UrbanWear",
      stock: 40,
      rating: 4.8,
      reviewCount: 156,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-07-20T10:00:00Z",
      salesCount: 85,
      color: ["Blue", "Black"],
      size: ["Medium", "Large", "X-Large"],
      dressStyle: "Casual",
      availability: "In Stock",
      material: "Denim",
      gender: "Men",
    },
    {
      id: "p_2003",
      title: "Minimalist Leather Sneakers",
      description: "Clean white sneakers made from sustainable vegan leather.",
      price: 110.0,
      images: ["https://picsum.photos/seed/p_2003/800/800"],
      category: "Fashion & Apparel",
      brand: "StepRight",
      stock: 65,
      rating: 4.6,
      reviewCount: 302,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-08-02T10:00:00Z",
      salesCount: 210,
      color: ["White", "Black"],
      size: ["Medium", "Large"],
      dressStyle: "Casual",
      availability: "In Stock",
      material: "Leather",
      gender: "Women",
    },
    {
      id: "p_2004",
      title: "Merino Wool Beanie",
      description: "Warm and itch-free ribbed beanie for winter.",
      price: 28.0,
      images: ["https://picsum.photos/seed/p_2004/800/800"],
      category: "Fashion & Apparel",
      brand: "EcoThread",
      stock: 80,
      rating: 4.9,
      reviewCount: 45,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-07-15T10:00:00Z",
      salesCount: 120,
      color: ["Black", "Orange", "Yellow"],
      size: ["Small", "Medium"],
      dressStyle: "Casual",
      availability: "In Stock",
      material: "Wool",
      gender: "Unisex",
    },
    {
      id: "p_2005",
      title: "Slim Fit Chino Pants",
      description: "Versatile stretch chinos suitable for work or weekend.",
      price: 54.0,
      images: ["https://picsum.photos/seed/p_2005/800/800"],
      category: "Fashion & Apparel",
      brand: "UrbanWear",
      stock: 55,
      rating: 4.4,
      reviewCount: 112,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-08-05T10:00:00Z",
      salesCount: 95,
      color: ["Black", "Blue"],
      size: ["Medium", "Large", "X-Large"],
      dressStyle: "Formal",
      availability: "In Stock",
      material: "Cotton",
      gender: "Men",
    },
    {
      id: "p_2006",
      title: "Oversized Pullover Hoodie",
      description: "Ultra-soft fleece hoodie with drop shoulders.",
      price: 65.0,
      images: ["https://picsum.photos/seed/p_2006/800/800"],
      category: "Fashion & Apparel",
      brand: "LoungeCo",
      stock: 90,
      rating: 4.7,
      reviewCount: 220,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-07-22T10:00:00Z",
      salesCount: 300,
      color: ["Pink", "Purple", "White"],
      size: ["Small", "Medium", "Large", "X-Large"],
      dressStyle: "Casual",
      availability: "In Stock",
      material: "Fleece",
      gender: "Women",
    },
    {
      id: "p_2007",
      title: "Kids Dinosaur Print Tee",
      description: "Fun graphic tee for toddlers.",
      price: 15.0,
      images: ["https://picsum.photos/seed/p_2007/800/800"],
      category: "Fashion & Apparel",
      brand: "LittleTots",
      stock: 35,
      rating: 4.5,
      reviewCount: 88,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-08-01T10:00:00Z",
      salesCount: 65,
      color: ["Yellow", "Green"],
      size: ["XX-Small", "X-Small"],
      dressStyle: "Party",
      availability: "In Stock",
      material: "Cotton",
      gender: "Kids",
    },
    {
      id: "p_2008",
      title: "Canvas Tote Bag",
      description:
        "Heavy-duty cotton canvas tote for groceries and essentials.",
      price: 18.0,
      images: ["https://picsum.photos/seed/p_2008/800/800"],
      category: "Fashion & Apparel",
      brand: "EcoThread",
      stock: 200,
      rating: 4.8,
      reviewCount: 150,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-07-10T10:00:00Z",
      salesCount: 400,
      color: ["White", "Black"],
      size: [],
      dressStyle: "Casual",
      availability: "In Stock",
      material: "Canvas",
      gender: "Unisex",
    },
    {
      id: "p_2009",
      title: "Athletic Running Shorts",
      description: "Quick-dry shorts with built-in liner and zip pockets.",
      price: 34.99,
      images: ["https://picsum.photos/seed/p_2009/800/800"],
      category: "Fashion & Apparel",
      brand: "ActiveLife",
      stock: 75,
      rating: 4.6,
      reviewCount: 95,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-08-06T10:00:00Z",
      salesCount: 140,
      color: ["Black", "Red", "Blue"],
      size: ["Medium", "Large"],
      dressStyle: "Gym",
      availability: "In Stock",
      material: "Polyester",
      gender: "Men",
    },
    {
      id: "p_2010",
      title: "Woven Braided Belt",
      description: "Elastic woven belt with a genuine leather trim.",
      price: 22.5,
      images: ["https://picsum.photos/seed/p_2010/800/800"],
      category: "Fashion & Apparel",
      brand: "UrbanWear",
      stock: 0,
      rating: 4.3,
      reviewCount: 42,
      vendor: {
        vendorId: "v_012",
        storeName: "Sustainable Basics",
        rating: 4.7,
      },
      variants: [],
      dateAdded: "2026-07-18T10:00:00Z",
      salesCount: 50,
      color: ["Black", "Brown"],
      size: ["Medium", "Large"],
      dressStyle: "Formal",
      availability: "Out of Stock",
      material: "Leather",
      gender: "Unisex",
    },

    // --- HOME & KITCHEN (Vendor: The Daily Grind) ---
    {
      id: "p_3001",
      title: "Artisan Pour-Over Coffee Kit",
      description:
        "Complete coffee set including a ceramic dripper and glass carafe.",
      price: 45.5,
      images: ["https://picsum.photos/seed/p_3001/800/800"],
      category: "Home & Kitchen",
      brand: "BrewMaster",
      stock: 0,
      rating: 4.2,
      reviewCount: 34,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-10T10:00:00Z",
      salesCount: 40,
      color: ["White", "Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Coffee Maker",
      material: "Ceramic",
      sizeCapacity: "1L",
    },
    {
      id: "p_3002",
      title: "Matte Ceramic Coffee Mug",
      description: "12oz handmade ceramic mug with a smooth matte finish.",
      price: 16.0,
      images: ["https://picsum.photos/seed/p_3002/800/800"],
      category: "Home & Kitchen",
      brand: "ClayWorks",
      stock: 110,
      rating: 4.9,
      reviewCount: 205,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-07T10:00:00Z",
      salesCount: 500,
      color: ["White", "Pink", "Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Mug",
      material: "Ceramic",
      sizeCapacity: "12oz",
    },
    {
      id: "p_3003",
      title: "Stainless Steel French Press",
      description: "Double-walled insulated French press for hot coffee.",
      price: 39.99,
      images: ["https://picsum.photos/seed/p_3003/800/800"],
      category: "Home & Kitchen",
      brand: "BrewMaster",
      stock: 40,
      rating: 4.7,
      reviewCount: 188,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-20T10:00:00Z",
      salesCount: 150,
      color: ["Black", "White"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Coffee Maker",
      material: "Stainless Steel",
      sizeCapacity: "34oz",
    },
    {
      id: "p_3004",
      title: "Electric Gooseneck Kettle",
      description: "Variable temperature kettle for precise pour-over brewing.",
      price: 89.0,
      images: ["https://picsum.photos/seed/p_3004/800/800"],
      category: "Home & Kitchen",
      brand: "BrewMaster",
      stock: 25,
      rating: 4.8,
      reviewCount: 142,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-06T10:00:00Z",
      salesCount: 110,
      color: ["Black", "White"],
      size: [],
      dressStyle: "",
      availability: "Pre-order",
      productType: "Kettle",
      material: "Stainless Steel",
      sizeCapacity: "1L",
    },
    {
      id: "p_3005",
      title: "Acacia Wood Cutting Board",
      description: "Thick, edge-grain wooden cutting board with juice groove.",
      price: 55.0,
      images: ["https://picsum.photos/seed/p_3005/800/800"],
      category: "Home & Kitchen",
      brand: "ChefPrep",
      stock: 30,
      rating: 4.6,
      reviewCount: 76,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-15T10:00:00Z",
      salesCount: 85,
      color: ["Brown"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Cutting Board",
      material: "Wood",
      sizeCapacity: "Large",
    },
    {
      id: "p_3006",
      title: "Japanese Steel Chef Knife",
      description: "8-inch professional chef knife with a carbon steel core.",
      price: 119.99,
      images: ["https://picsum.photos/seed/p_3006/800/800"],
      category: "Home & Kitchen",
      brand: "BladePro",
      stock: 15,
      rating: 4.9,
      reviewCount: 310,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-01T10:00:00Z",
      salesCount: 200,
      color: ["Black", "White"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Knife",
      material: "Steel",
      sizeCapacity: "8 inch",
    },
    {
      id: "p_3007",
      title: "Waffle Weave Kitchen Towels",
      description: "Set of 4 ultra-absorbent microfiber kitchen towels.",
      price: 22.0,
      images: ["https://picsum.photos/seed/p_3007/800/800"],
      category: "Home & Kitchen",
      brand: "HomeLinens",
      stock: 150,
      rating: 4.5,
      reviewCount: 65,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-05T10:00:00Z",
      salesCount: 95,
      color: ["White", "Blue", "Green"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Towel",
      material: "Microfiber",
      sizeCapacity: "Set of 4",
    },
    {
      id: "p_3008",
      title: "Ceramic Planter Pot",
      description: "Minimalist indoor plant pot with wooden stand.",
      price: 34.5,
      images: ["https://picsum.photos/seed/p_3008/800/800"],
      category: "Home & Kitchen",
      brand: "BotanyCo",
      stock: 0,
      rating: 4.7,
      reviewCount: 104,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-08-07T10:00:00Z",
      salesCount: 130,
      color: ["White", "Black"],
      size: [],
      dressStyle: "",
      availability: "Out of Stock",
      productType: "Planter",
      material: "Ceramic",
      sizeCapacity: "Medium",
    },
    {
      id: "p_3009",
      title: "Scented Soy Candle",
      description: "Lavender and vanilla hand-poured soy wax candle.",
      price: 24.0,
      images: ["https://picsum.photos/seed/p_3009/800/800"],
      category: "Home & Kitchen",
      brand: "Lumina",
      stock: 0,
      rating: 4.8,
      reviewCount: 220,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-28T10:00:00Z",
      salesCount: 300,
      color: ["White", "Pink"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Candle",
      material: "Soy Wax",
      sizeCapacity: "8oz",
    },
    {
      id: "p_3010",
      title: "Cast Iron Skillet",
      description:
        "10-inch pre-seasoned cast iron skillet for versatile cooking.",
      price: 42.99,
      images: ["https://picsum.photos/seed/p_3010/800/800"],
      category: "Home & Kitchen",
      brand: "ChefPrep",
      stock: 60,
      rating: 4.6,
      reviewCount: 540,
      vendor: { vendorId: "v_089", storeName: "The Daily Grind", rating: 4.9 },
      variants: [],
      dateAdded: "2026-07-02T10:00:00Z",
      salesCount: 700,
      color: ["Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Cookware",
      material: "Cast Iron",
      sizeCapacity: "10 inch",
    },

    // --- HEALTH & BEAUTY (Vendor: Glow Up Beauty) ---
    {
      id: "p_4001",
      title: "Hydrating Facial Cleanser",
      description: "Gentle daily cleanser with hyaluronic acid and ceramides.",
      price: 18.0,
      images: ["https://picsum.photos/seed/p_4001/800/800"],
      category: "Health & Beauty",
      brand: "PureSkin",
      stock: 140,
      rating: 4.7,
      reviewCount: 315,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-08-04T10:00:00Z",
      salesCount: 410,
      color: ["White"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Cleanser",
      skinHairType: "Dry",
      concern: "Hydration",
      sizeQuantity: "8oz",
    },
    {
      id: "p_4002",
      title: "Vitamin C Brightening Serum",
      description: "Antioxidant serum to even skin tone and boost radiance.",
      price: 34.0,
      images: ["https://picsum.photos/seed/p_4002/800/800"],
      category: "Health & Beauty",
      brand: "GlowLab",
      stock: 75,
      rating: 4.5,
      reviewCount: 280,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-07-15T10:00:00Z",
      salesCount: 150,
      color: ["Orange", "White"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Serum",
      skinHairType: "All",
      concern: "Anti-Aging",
      sizeQuantity: "1oz",
    },
    {
      id: "p_4003",
      title: "Nourishing Body Lotion",
      description: "Rich shea butter lotion for dry and sensitive skin.",
      price: 22.5,
      images: ["https://picsum.photos/seed/p_4003/800/800"],
      category: "Health & Beauty",
      brand: "PureSkin",
      stock: 0,
      rating: 4.6,
      reviewCount: 150,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-07-22T10:00:00Z",
      salesCount: 90,
      color: ["White"],
      size: [],
      dressStyle: "",
      availability: "Out of Stock",
      productType: "Lotion",
      skinHairType: "Dry",
      concern: "Hydration",
      sizeQuantity: "16oz",
    },
    {
      id: "p_4004",
      title: "Matte Liquid Lipstick",
      description: "Long-lasting, transfer-proof red matte lipstick.",
      price: 16.0,
      images: ["https://picsum.photos/seed/p_4004/800/800"],
      category: "Health & Beauty",
      brand: "Aura",
      stock: 0,
      rating: 4.4,
      reviewCount: 410,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-08-07T10:00:00Z",
      salesCount: 320,
      color: ["Red", "Pink"],
      size: [],
      dressStyle: "Party",
      availability: "In Stock",
      productType: "Makeup",
      skinHairType: "All",
      concern: "None",
      sizeQuantity: "0.2oz",
    },
    {
      id: "p_4005",
      title: "Organic Rosehip Oil",
      description: "100% pure cold-pressed oil for face, hair, and nails.",
      price: 28.0,
      images: ["https://picsum.photos/seed/p_4005/800/800"],
      category: "Health & Beauty",
      brand: "BotanyCo",
      stock: 50,
      rating: 4.8,
      reviewCount: 195,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-07-10T10:00:00Z",
      salesCount: 180,
      color: ["Yellow", "Orange"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Oil",
      skinHairType: "Oily",
      concern: "Acne",
      sizeQuantity: "2oz",
    },
    {
      id: "p_4006",
      title: "Bamboo Toothbrush Set",
      description: "Eco-friendly pack of 4 biodegradable bamboo toothbrushes.",
      price: 12.0,
      images: ["https://picsum.photos/seed/p_4006/800/800"],
      category: "Health & Beauty",
      brand: "EcoThread",
      stock: 200,
      rating: 4.9,
      reviewCount: 88,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-07-05T10:00:00Z",
      salesCount: 300,
      color: ["Green", "White"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Oral Care",
      skinHairType: "All",
      concern: "None",
      sizeQuantity: "Set of 4",
    },
    {
      id: "p_4007",
      title: "Charcoal Face Mask",
      description: "Purifying clay mask to unclog pores and detoxify skin.",
      price: 26.5,
      images: ["https://picsum.photos/seed/p_4007/800/800"],
      category: "Health & Beauty",
      brand: "GlowLab",
      stock: 45,
      rating: 4.3,
      reviewCount: 134,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-08-01T10:00:00Z",
      salesCount: 120,
      color: ["Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Mask",
      skinHairType: "Oily",
      concern: "Acne",
      sizeQuantity: "4oz",
    },
    {
      id: "p_4008",
      title: "Sulfate-Free Shampoo",
      description: "Gentle lathering shampoo for color-treated hair.",
      price: 20.0,
      images: ["https://picsum.photos/seed/p_4008/800/800"],
      category: "Health & Beauty",
      brand: "StrandCare",
      stock: 110,
      rating: 4.5,
      reviewCount: 220,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-07-28T10:00:00Z",
      salesCount: 250,
      color: ["White", "Pink"],
      size: [],
      dressStyle: "",
      availability: "Pre-order",
      productType: "Shampoo",
      skinHairType: "Dry",
      concern: "Hydration",
      sizeQuantity: "12oz",
    },
    {
      id: "p_4009",
      title: "Exfoliating Body Scrub",
      description: "Sugar and coffee body scrub for smooth, glowing skin.",
      price: 19.99,
      images: ["https://picsum.photos/seed/p_4009/800/800"],
      category: "Health & Beauty",
      brand: "PureSkin",
      stock: 80,
      rating: 4.6,
      reviewCount: 167,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-07-12T10:00:00Z",
      salesCount: 160,
      color: ["Brown", "Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      productType: "Scrub",
      skinHairType: "All",
      concern: "Exfoliation",
      sizeQuantity: "8oz",
    },
    {
      id: "p_4010",
      title: "Signature Eau de Parfum",
      description:
        "Fresh floral fragrance with notes of jasmine and sandalwood.",
      price: 85.0,
      images: ["https://picsum.photos/seed/p_4010/800/800"],
      category: "Health & Beauty",
      brand: "Aura",
      stock: 30,
      rating: 4.7,
      reviewCount: 432,
      vendor: { vendorId: "v_077", storeName: "Glow Up Beauty", rating: 4.8 },
      variants: [],
      dateAdded: "2026-08-06T10:00:00Z",
      salesCount: 380,
      color: ["Pink", "Yellow"],
      size: [],
      dressStyle: "Formal",
      availability: "In Stock",
      productType: "Fragrance",
      skinHairType: "All",
      concern: "None",
      sizeQuantity: "1.7oz",
    },

    // --- SPORTS & OUTDOORS (Vendor: Active Life) ---
    {
      id: "p_5001",
      title: "Non-Slip Yoga Mat",
      description: "Thick, eco-friendly TPE yoga mat with alignment lines.",
      price: 35.0,
      images: ["https://picsum.photos/seed/p_5001/800/800"],
      category: "Sports & Outdoors",
      brand: "ZenFit",
      stock: 120,
      rating: 4.8,
      reviewCount: 512,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-07-01T10:00:00Z",
      salesCount: 600,
      color: ["Purple", "Blue", "Pink"],
      size: ["Large"],
      dressStyle: "Gym",
      availability: "In Stock",
      sportType: "Yoga",
      productType: "Equipment",
    },
    {
      id: "p_5002",
      title: "Insulated Water Bottle",
      description:
        "Stainless steel 32oz bottle keeps drinks cold for 24 hours.",
      price: 25.0,
      images: ["https://picsum.photos/seed/p_5002/800/800"],
      category: "Sports & Outdoors",
      brand: "HydroCore",
      stock: 250,
      rating: 4.9,
      reviewCount: 890,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-08-05T10:00:00Z",
      salesCount: 850,
      color: ["Black", "White", "Red", "Blue"],
      size: [],
      dressStyle: "Gym",
      availability: "In Stock",
      sportType: "Cycling",
      productType: "Accessory",
    },
    {
      id: "p_5003",
      title: "Adjustable Dumbbell Set",
      description: "Space-saving dumbbells adjusting from 5 to 52.5 lbs.",
      price: 199.99,
      images: ["https://picsum.photos/seed/p_5003/800/800"],
      category: "Sports & Outdoors",
      brand: "IronTech",
      stock: 15,
      rating: 4.7,
      reviewCount: 320,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-07-20T10:00:00Z",
      salesCount: 220,
      color: ["Black", "Red"],
      size: [],
      dressStyle: "Gym",
      availability: "In Stock",
      sportType: "Fitness",
      productType: "Equipment",
    },
    {
      id: "p_5004",
      title: "Resistance Band Kit",
      description: "Set of 5 color-coded bands with handles and door anchor.",
      price: 29.99,
      images: ["https://picsum.photos/seed/p_5004/800/800"],
      category: "Sports & Outdoors",
      brand: "FitGear",
      stock: 85,
      rating: 4.5,
      reviewCount: 215,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-08-02T10:00:00Z",
      salesCount: 190,
      color: ["Red", "Blue", "Green", "Yellow", "Black"],
      size: [],
      dressStyle: "Gym",
      availability: "In Stock",
      sportType: "Fitness",
      productType: "Equipment",
    },
    {
      id: "p_5005",
      title: "Lightweight Backpacking Tent",
      description: "2-person, 3-season tent for hiking and camping.",
      price: 145.0,
      images: ["https://picsum.photos/seed/p_5005/800/800"],
      category: "Sports & Outdoors",
      brand: "TrailBlaze",
      stock: 0,
      rating: 4.6,
      reviewCount: 98,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-07-15T10:00:00Z",
      salesCount: 75,
      color: ["Green", "Orange"],
      size: ["Medium", "Large"],
      dressStyle: "",
      availability: "Out of Stock",
      sportType: "Camping",
      productType: "Equipment",
    },
    {
      id: "p_5006",
      title: "Mummy Sleeping Bag",
      description: "Compact sleeping bag rated for 20-degree weather.",
      price: 75.0,
      images: ["https://picsum.photos/seed/p_5006/800/800"],
      category: "Sports & Outdoors",
      brand: "TrailBlaze",
      stock: 0,
      rating: 4.4,
      reviewCount: 75,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-08-07T10:00:00Z",
      salesCount: 110,
      color: ["Blue", "Black"],
      size: ["Medium", "Large"],
      dressStyle: "",
      availability: "In Stock",
      sportType: "Camping",
      productType: "Equipment",
    },
    {
      id: "p_5007",
      title: "LED Headlamp",
      description: "Rechargeable waterproof headlamp for running and camping.",
      price: 22.99,
      images: ["https://picsum.photos/seed/p_5007/800/800"],
      category: "Sports & Outdoors",
      brand: "Lumina",
      stock: 150,
      rating: 4.7,
      reviewCount: 420,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-07-10T10:00:00Z",
      salesCount: 350,
      color: ["Black", "Yellow"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      sportType: "Running",
      productType: "Accessory",
    },
    {
      id: "p_5008",
      title: "Speed Jump Rope",
      description: "Adjustable steel wire jump rope with ball bearings.",
      price: 14.5,
      images: ["https://picsum.photos/seed/p_5008/800/800"],
      category: "Sports & Outdoors",
      brand: "FitGear",
      stock: 200,
      rating: 4.8,
      reviewCount: 180,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-08-01T10:00:00Z",
      salesCount: 280,
      color: ["Black", "Red"],
      size: [],
      dressStyle: "Gym",
      availability: "In Stock",
      sportType: "Fitness",
      productType: "Equipment",
    },
    {
      id: "p_5009",
      title: "Foam Roller",
      description:
        "High-density foam roller for deep tissue massage and recovery.",
      price: 19.99,
      images: ["https://picsum.photos/seed/p_5009/800/800"],
      category: "Sports & Outdoors",
      brand: "ZenFit",
      stock: 60,
      rating: 4.5,
      reviewCount: 155,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-07-22T10:00:00Z",
      salesCount: 130,
      color: ["Blue", "Black"],
      size: ["Large"],
      dressStyle: "Gym",
      availability: "In Stock",
      sportType: "Yoga",
      productType: "Accessory",
    },
    {
      id: "p_5010",
      title: "Hiking Backpack 50L",
      description: "Durable pack with internal frame and rain cover.",
      price: 110.0,
      images: ["https://picsum.photos/seed/p_5010/800/800"],
      category: "Sports & Outdoors",
      brand: "TrailBlaze",
      stock: 28,
      rating: 4.7,
      reviewCount: 210,
      vendor: { vendorId: "v_044", storeName: "Active Life", rating: 4.6 },
      variants: [],
      dateAdded: "2026-08-06T10:00:00Z",
      salesCount: 175,
      color: ["Green", "Black"],
      size: ["Large"],
      dressStyle: "",
      availability: "Pre-order",
      sportType: "Camping",
      productType: "Equipment",
    },

    // --- TOYS (Vendor: PlayTime) ---
    {
      id: "p_6001",
      title: "Building Blocks Set",
      description: "500-piece colorful building block set.",
      price: 39.99,
      images: ["https://picsum.photos/seed/p_6001/800/800"],
      category: "Toys",
      brand: "BlockBuilder",
      stock: 45,
      rating: 4.8,
      reviewCount: 130,
      vendor: { vendorId: "v_021", storeName: "PlayTime", rating: 4.7 },
      variants: [],
      dateAdded: "2026-08-01T10:00:00Z",
      salesCount: 210,
      color: ["Red", "Blue", "Green", "Yellow"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      ageGroup: "3-5 Years",
      toyType: "Building",
      genderAudience: "Unisex",
      educational: "Yes",
    },
    {
      id: "p_6002",
      title: "Remote Control Car",
      description: "High-speed RC car with rechargeable battery.",
      price: 49.5,
      images: ["https://picsum.photos/seed/p_6002/800/800"],
      category: "Toys",
      brand: "Speedster",
      stock: 20,
      rating: 4.6,
      reviewCount: 85,
      vendor: { vendorId: "v_021", storeName: "PlayTime", rating: 4.7 },
      variants: [],
      dateAdded: "2026-07-25T10:00:00Z",
      salesCount: 110,
      color: ["Red", "Black"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      ageGroup: "6-8 Years",
      toyType: "Action",
      genderAudience: "Boys",
      educational: "No",
    },
    {
      id: "p_6003",
      title: "Educational Robot Kit",
      description: "Learn coding with this programmable robot.",
      price: 89.99,
      images: ["https://picsum.photos/seed/p_6003/800/800"],
      category: "Toys",
      brand: "TechKids",
      stock: 15,
      rating: 4.9,
      reviewCount: 320,
      vendor: { vendorId: "v_021", storeName: "PlayTime", rating: 4.7 },
      variants: [],
      dateAdded: "2026-08-05T10:00:00Z",
      salesCount: 175,
      color: ["White", "Blue"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      ageGroup: "9-12 Years",
      toyType: "Electronic",
      genderAudience: "Unisex",
      educational: "Yes",
    },
    {
      id: "p_6004",
      title: "Plush Teddy Bear",
      description: "Soft and cuddly 18-inch teddy bear.",
      price: 19.99,
      images: ["https://picsum.photos/seed/p_6004/800/800"],
      category: "Toys",
      brand: "CuddleCo",
      stock: 100,
      rating: 4.7,
      reviewCount: 450,
      vendor: { vendorId: "v_021", storeName: "PlayTime", rating: 4.7 },
      variants: [],
      dateAdded: "2026-07-10T10:00:00Z",
      salesCount: 500,
      color: ["Brown"],
      size: [],
      dressStyle: "",
      availability: "In Stock",
      ageGroup: "0-2 Years",
      toyType: "Plush",
      genderAudience: "Unisex",
      educational: "No",
    },
  ],
};

const DUMMY_REVIEWS = [
  {
    id: 1,
    user: "Samantha D.",
    rating: 5,
    date: "August 14, 2023",
    text: "I absolutely love this product! The design is unique and feels so comfortable. As a fellow designer, I appreciate the attention to detail. It's become my favorite go-to.",
    verified: true,
  },
  {
    id: 2,
    user: "Alex M.",
    rating: 4,
    date: "August 15, 2023",
    text: "This exceeded my expectations! The colors are vibrant and quality is top-notch. Being quite picky about aesthetics, this definitely gets a thumbs up from me.",
    verified: true,
  },
  {
    id: 3,
    user: "Ethan R.",
    rating: 4.5,
    date: "August 16, 2023",
    text: "A must-have for anyone who appreciates good design. The minimalistic yet stylish pattern caught my eye, and the fit is perfect. I can see the designer's touch in every aspect.",
    verified: true,
  },
  {
    id: 4,
    user: "Olivia P.",
    rating: 4,
    date: "August 17, 2023",
    text: "As a UI/UX enthusiast, I value simplicity and functionality. This not only represents those principles but also feels great to use. It's evident that the designer poured their creativity into making it stand out.",
    verified: true,
  },
  {
    id: 5,
    user: "Liam K.",
    rating: 4,
    date: "August 18, 2023",
    text: "A fusion of comfort and creativity. It speaks volumes about the designer's skill. It's like having a piece of art that reflects my passion for both design and utility.",
    verified: true,
  },
  {
    id: 6,
    user: "Ava H.",
    rating: 4.5,
    date: "August 19, 2023",
    text: "I'm not just using a product, I'm experiencing a piece of design philosophy. The intricate details and thoughtful layout make it a true conversation starter.",
    verified: true,
  },
];

initialState.items = initialState.items.map((item) => ({
  ...item,
  reviews: DUMMY_REVIEWS,
}));

const productSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    // You can add more product-related reducers here (e.g. setProducts, addProduct)
  },
});

export const selectAllProducts = (state) => state.products.items;

export default productSlice.reducer;
